services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Wexample\SymfonyTranslations\:
        resource: '../../{Command,Service,Twig}'
        tags: ['controller.service_arguments']

    # Override translation service.
    Wexample\SymfonyTranslations\Translation\Translator:
      decorates: translator
      arguments:
        - '@translator.default'
      public: false